services:
  local-postgres-service:
    container_name: traillers-local-db
    image: postgres:16.2-alpine
    restart: always
    ports:
      - "5000:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./postgres:/var/lib/postgresql/data